[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
create_core_asset_example = "D9dejLvL66DFJq52bVE1dNUmdUZkeqNYmcW1sqh4HrVY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ytakahashi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
