[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
create_core_asset_example = "7VYB91EAPtxaZfSehC7LCCB8D6FAroeH8ZYsanNZdCvF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ytakahashi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
